server:
  port: 8081

spring:
  application:
    name: eta-service
  
  profiles:
    active: dev
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/logistics_eta
      auto-index-creation: true
  
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
        streams:
          binder:
            configuration:
              default:
                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value.serde: org.springframework.kafka.support.serializer.JsonSerde
      bindings:
        eta-calculated-out:
          destination: eta-calculated
          contentType: application/json
        telematics-in:
          destination: telematics-updates
          contentType: application/json
        traffic-in:
          destination: traffic-updates
          contentType: application/json

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.dpd.uk.eta: DEBUG
    org.springframework.cloud.stream: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# External API configurations
external:
  traffic:
    api-key: ${TRAFFIC_API_KEY:your-traffic-api-key}
    base-url: https://api.traffic-service.com/v1
    timeout: 5000
  
  mapping:
    api-key: ${MAPPING_API_KEY:your-mapping-api-key}
    base-url: https://atlas.microsoft.com/map
    timeout: 10000

# ETA calculation configuration
eta:
  calculation:
    default-confidence: MEDIUM
    max-prediction-hours: 24
    cache-ttl-minutes: 15
    batch-size: 100
    refresh-interval-seconds: 30
  
  factors:
    traffic-weight: 0.4
    distance-weight: 0.3
    historical-weight: 0.2
    depot-constraints-weight: 0.1
