server:
  port: 8083

spring:
  application:
    name: returns-service
  
  profiles:
    active: dev
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/logistics_returns
      auto-index-creation: true
  
  redis:
    host: localhost
    port: 6379
    database: 2
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
        streams:
          binder:
            configuration:
              default:
                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value.serde: org.springframework.kafka.support.serializer.JsonSerde
      bindings:
        return-initiated-out:
          destination: return-initiated
          contentType: application/json
        return-approved-out:
          destination: return-approved
          contentType: application/json
        return-picked-up-out:
          destination: return-picked-up
          contentType: application/json
        return-processed-out:
          destination: return-processed
          contentType: application/json

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.dpd.uk.returns: DEBUG
    org.springframework.statemachine: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Returns configuration
returns:
  ttl:
    default-hours: 24
    max-hours: 72
    warning-hours: 2
  
  approval:
    auto-approve-threshold: 50.0
    manual-review-threshold: 100.0
    max-approval-hours: 4
  
  processing:
    batch-size: 100
    processing-delay-minutes: 5
    max-retry-attempts: 3
  
  notifications:
    email-enabled: true
    sms-enabled: true
    webhook-enabled: true
