# Common configuration for all microservices
spring:
  application:
    name: common-lib
  
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    time-zone: UTC
  
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 10000
            logger-level: basic
      compression:
        request:
          enabled: true
        response:
          enabled: true

# Common validation settings
validation:
  message:
    source: classpath:messages/validation-messages.properties

# Common cache settings
cache:
  default-ttl: 300 # 5 minutes
  max-entries: 1000

# Common logging configuration
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"
  
  level:
    com.dpd.uk: INFO
    org.springframework.cloud: INFO
    org.springframework.web: INFO
    org.springframework.data: INFO

# Common metrics configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
      slo:
        http.server.requests: 50ms, 100ms, 200ms, 500ms

# Common security settings
security:
  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

# Common error handling
error:
  include-message: always
  include-binding-errors: always
  include-stacktrace: on_param
  include-exception: false
